// SPDX-FileCopyrightText: 2025 Evaisa <evagiacosa1@gmail.com>
// SPDX-FileCopyrightText: 2025 EvaisaDev <mail@evaisa.dev>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared.Access.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Content.Shared.CCVar;

namespace Content.Client._Funkystation.NanoChat;

[GenerateTypedNameReferences]
public sealed partial class CreateGroupChatPopup : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public event Action<string>? OnGroupCreated;
    private int _maxNameLength;

    public CreateGroupChatPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ContentsContainer.Margin = new Thickness(3);

        // Button handlers
        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        // Input validation
        GroupNameInput.OnTextEntered += _ => CreateGroup();

        _maxNameLength = _cfg.GetCVar(CCVars.MaxNameLength);

        GroupNameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > _maxNameLength)
                GroupNameInput.Text = args.Text[.._maxNameLength];
            ValidateInputs();
        };
    }

    private void ValidateInputs()
    {
        var isValid = !string.IsNullOrWhiteSpace(GroupNameInput.Text);
        CreateButton.Disabled = !isValid;
    }

    private void CreateGroup()
    {
        if (CreateButton.Disabled)
            return;

        var name = GroupNameInput.Text.Trim();
        OnGroupCreated?.Invoke(name);
        Close();
    }

    public void ClearInputs()
    {
        GroupNameInput.Text = string.Empty;
        ValidateInputs();
    }
}
