- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-description-mail-carrier
  startingGear: MailCarrierGear
  alwaysUseSpawner: true
  playTimeTracker: JobMailCarrier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  icon: "JobIconMailCarrier"
  supervisors: job-supervisors-sr
  weight: 90 # Frontier
  displayWeight: 30 # Frontier
  canBeAntag: false
  access:
  - Cargo # Aurora's Song - Cargo access is being undeprecated
  - External # Frontier
  - Maintenance
  - Service
  - Mail # Frontier
  - Aurora # Frontier - Aurora Song - Changed from Frontier to Aurora
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: MailCarrierGear
  equipment:
    head: ClothingHeadMailCarrier
    eyes: ClothingEyesHudMail
    id: CourierPDA
#    ears: ClothingHeadsetService # Frontier - ClothingHeadsetCargo<ClothingHeadsetService
    belt: NFMailBag
  storage:
    back: # Aurora's Song - moved service encryption key to the appropriate section
    - HandheldCrewMonitor # Frontier
    - ShipVoucherFrontierMailCarrier # Frontier
    - MailMetricsCartridge # Frontier
    - CrayonBox # Aurora's Song - for labeling mail areas
  encryptionKeys: # Aurora's Song - Added traffic, shipboard, and service encryption keys
  - EncryptionKeyTraffic
  - EncryptionKeyShipboard
  - EncryptionKeyService

- type: chameleonOutfit
  id: MailCarrierChameleonOutfit
  job: MailCarrier
  hasMindShield: true
