// Aurora Song - AS Medical Bounty System
// Based on New Frontier Station 14's Medical Bounty System
// Original implementation: https://github.com/new-frontiers-14/frontier-station-14
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._AS.Medical;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AS.Medical.UI;

/// <summary>
/// Aurora Song: UI window for AS medical bounty redemption
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ASMedicalBountyRedemptionMenu : FancyWindow
{
    public Action? SellRequested;

    public ASMedicalBountyRedemptionMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    /// <summary>
    /// Aurora Song: Update the UI based on the current state
    /// </summary>
    public void UpdateState(ASMedicalBountyRedemptionUIState message)
    {
        switch (message.BountyStatus)
        {
            case ASMedicalBountyRedemptionStatus.NoBody:
            default:
                BodyLabel.Text = Loc.GetString("as-medical-bounty-redemption-body-label-no-items");
                RedeemLabel.Text = Loc.GetString("as-medical-bounty-redemption-redeem-label-no-items");
                SellButton.Disabled = true;
                break;
            case ASMedicalBountyRedemptionStatus.NoBounty:
                BodyLabel.Text = Loc.GetString("as-medical-bounty-redemption-body-label-body-present");
                RedeemLabel.Text = Loc.GetString("as-medical-bounty-redemption-redeem-label-no-bounty");
                SellButton.Disabled = true;
                break;
            case ASMedicalBountyRedemptionStatus.TooDamaged:
                BodyLabel.Text = Loc.GetString("as-medical-bounty-redemption-body-label-valid-bounty");
                RedeemLabel.Text = Loc.GetString("as-medical-bounty-redemption-redeem-label-too-much-damage");
                SellButton.Disabled = true;
                break;
            case ASMedicalBountyRedemptionStatus.NotAlive:
                BodyLabel.Text = Loc.GetString("as-medical-bounty-redemption-body-label-valid-bounty");
                RedeemLabel.Text = Loc.GetString("as-medical-bounty-redemption-redeem-label-not-alive");
                SellButton.Disabled = true;
                break;
            case ASMedicalBountyRedemptionStatus.Valid:
                BodyLabel.Text = Loc.GetString("as-medical-bounty-redemption-body-label-valid-bounty");
                if (message.PaidToStation)
                    RedeemLabel.Text = Loc.GetString("as-medical-bounty-redemption-redeem-label-valid-bounty-to-station", ("amount", BankSystemExtensions.ToSpesoString(message.BountyValue)));
                else
                    RedeemLabel.Text = Loc.GetString("as-medical-bounty-redemption-redeem-label-valid-bounty", ("amount", BankSystemExtensions.ToSpesoString(message.BountyValue)));
                SellButton.Disabled = false;
                break;
        }
    }
}
