- type: job
  id: Valet
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobValet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ValetGear
  alwaysUseSpawner: true
  icon: "JobIconValet"
  supervisors: job-supervisors-sr
  weight: 60
  displayWeight: 10
  canBeAntag: false
  access:
  - Cargo # Aurora's Song - Cargo access is being undeprecated
  - Maintenance
  - External
  - Service
  - Aurora # Aurora Song - Changed from Frontier to Aurora
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: ValetGear
  equipment:
    head: ClothingHeadHatBellhop
    gloves: ClothingHandsGlovesColorWhite
    id: ValetPDA
  storage:
    back: # Aurora's Song - moved service encryption key to the appropriate section
    - ShipVoucherFrontierValet
  encryptionKeys: # Aurora's Song - Added traffic, shipboard, and service encryption keys
  - EncryptionKeyGreeting
  - EncryptionKeyTraffic
  - EncryptionKeyShipboard
  - EncryptionKeyService

- type: chameleonOutfit
  id: ValetChameleonOutfit
  job: Valet
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBellhop
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
