using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class DepartmentWhitelistPanel : PanelContainer
{
    public Action<ProtoId<JobPrototype>, bool>? OnSetJob;

    public DepartmentWhitelistPanel(DepartmentPrototype department, IPrototypeManager proto, HashSet<ProtoId<JobPrototype>> whitelists) // AS: Removing global whitelists from role whitelist checks
    {
        RobustXamlLoader.Load(this);

        var anyValid = false;//
        var allWhitelisted = true;
        var grey = Color.FromHex("#ccc");
        foreach (var id in department.Roles)
        {
            var thisJob = id; // closure capturing funny

            // Frontier: skip non-whitelisted roles, cache prototype
            var jobProto = proto.Index(id);
            if (!jobProto.Whitelisted)
                continue;
            else
                anyValid = true;
            // End Frontier

            var button = new CheckBox();
            button.Text = jobProto.LocalizedName;
            if (!jobProto.Whitelisted)
                button.Modulate = grey; // Let admins know whitelisting this job is only for futureproofing.
            button.Pressed = whitelists.Contains(id); // AS: Removing global whitelists from role whitelist checks
            button.OnPressed += _ => OnButtonPressed(thisJob, button); // AS: Removing global whitelists from role whitelist checks
            JobsContainer.AddChild(button);

            allWhitelisted &= button.Pressed;
        }

        if (!anyValid) // Frontier: hide checkbox set if no valid events
            Visible = false;  // Frontier

        Department.Text = Loc.GetString(department.Name);
        Department.Modulate = department.Color;
        Department.Pressed = allWhitelisted;
        Department.OnPressed += args => OnDepartmentPressed(department, proto, whitelists); // AS: Removing global whitelists from role whitelist checks
    }

    // Frontier: global whitelist handling
    private void OnButtonPressed(ProtoId<JobPrototype> thisJob, CheckBox button) // AS: Removing global whitelists from role whitelist checks
    {
        OnSetJob?.Invoke(thisJob, button.Pressed); // AS: Removing global whitelists from role whitelist checks
    }

    private void OnDepartmentPressed(DepartmentPrototype department, IPrototypeManager proto, HashSet<ProtoId<JobPrototype>> whitelists) // AS: Removing global whitelists from role whitelist checks
    {
        // AS: Removing global whitelists from role whitelist checks
        foreach (var id in department.Roles)
        {
            // only request to whitelist roles that aren't already whitelisted, and vice versa - Frontier: roles must be whitelisted
            if (whitelists.Contains(id) != Department.Pressed && proto.Index(id).Whitelisted)
                OnSetJob?.Invoke(id, Department.Pressed);
        }
    }
    // End Frontier
}
