- type: department
  id: Aurora # Aurora Song - Changed from Frontier to Aurora
  name: department-Frontier
  description: department-NF-description
  color: "#334E6D"
  weight: 50 # accounted for in jobs
  roles:
  - ColonialRepresentative # Aurora's Song - changed from Station Representative to Colonial Representative
#  - DirectorOfCare # Aurora's Song - moved DoC to Aurora Clinic
  - StationTrafficController
  - Service # Aurora
  - Valet # nyano
  - NFJanitor
  - MailCarrier # nyano
  - SecurityGuard

- type: department
  id: Antag
  name: department-Antag
  description: department-NFAntag-description
  color: "#DE3A3A"
  weight: -20 # accounted for in jobs
  roles:
  - NFPirateCaptain
  - NFPirateFirstMate
  - NFPirate
  - Prisoner #nyano
