using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client._AS.License.UI;

[GenerateTypedNameReferences]
public sealed partial class LicenseConsoleMenu : FancyWindow
{
    public Action? PrintLicense;

    public LicenseConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        PrintButton.OnPressed += OnPrintPressed;
    }

    private void OnPrintPressed(BaseButton.ButtonEventArgs obj)
    {
        PrintLicense?.Invoke();
    }
}
